language: csharp
mono: none
dotnet: 2.1.402

before_install: 
 - cd Overstarch

install:
 - dotnet restore 
 
script:
 - |
  if [ "${TRAVIS_BRANCH}" == "master" ]; then
    dotnet pack -o $HOME /p:Version=$PACKAGE_VERSION
  fi
 - |
  if [ "${TRAVIS_BRANCH}" == "development" ]; then
    dotnet pack -o $HOME /p:Version=$PACKAGE_VERSION-beta-$TRAVIS_BUILD_NUMBER
  fi
 - dotnet nuget push $HOME/*.nupkg -k $NUGETKEY -s $NUGETURL
 
after_success:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
  
after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL
 
env:
 - PACKAGE_VERSION=2.0.0 