language: csharp
mono: none
dotnet: 2.1.402

install:
 - dotnet restore

script:
 - |
  if [ "${TRAVIS_BRANCH}" == "master" ]; then
    dotnet pack -o $HOME /p:Version=$VERSION
  fi
 - |
  if [ "${TRAVIS_BRANCH}" == "development" ]; then
    dotnet pack -o $HOME /p:Version=$VERSION_$TRAVIS_BUILD_NUMBER-beta
  fi
 - dotnet nuget push $HOME/*.nupkg -k $NUGETKEY -s $NUGETURL
 
env:
 - VERSION=1.0.0 