language: visualbasic
mono: none
dotnet: 2.1.0

install:
 - dotnet restore

script:
 - dotnet pack
 
deploy:
  skip_cleanup: true
  provider: script
  script: dotnet nuget push *.nupkg -k $NUGETKEY
  on:
    branch: development
 